In [ ]:
''' Numpy's are the python library used for scientific computing and array manipulation.
-> It also functions as a mathematical library such as linear algebra, matrices, etc.
-> It is a open source platform and anyone can use it freely.
-> It is a multi-dimensional array object.
-> IT stands for Numerical Python.
-> They are slow process.
-> Locality of reference means that they are stored in a memory block of fixed size. which means that they are stored in contiguous memory block. it makes easier to access the data. and manipulate the data.
'''

" Numpy's are the python library used for scientific computing and array manipulation. \n-> It also functions as a mathematical library such as linear algebra, matrices, etc.\n-> It is a open source platform and anyone can use it freely. \n"

In [ ]:
#Creation of Array
import numpy as np # np is alias name for numpy
a = np.array([1,2,3,4,5]) # 1D array
print(a)

[1 2 3 4 5]


In [ ]:
# Checking version of numpy
import numpy as np
print(np.__version__)

1.23.5


In [ ]:
# Checking Type of data variables.
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

# or print(a.dtype) can be used instead of type(a).
# if we use type(a) it will give output as <class 'numpy.ndarray'>
# if use {} instead of [] we will get output as object, whereas if we use [] it give int64 as output.

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# Dimension of array : It is a level of array in depth.
import numpy as np
a = np.array(114) # 0D - Scalar
a1 = np.array([1,2,3,4,5,6]) #1D - Vector.
a2 = np.array([[1,2,3],[4,5,6]]) # 2D - Matrix.
a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # 3D - Tensor.
print(a)
print(a1)
print(a2)
print(a3)

114
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# ndmin: It is used to specify the minimum dimension of the array
import numpy as np
a = np.array([1,2,3,4,5], ndmin = 4)
print(a)
print(a.ndim)

[[[[1 2 3 4 5]]]]
4


In [ ]:
#Array Accessing Elements
# Array index starts from 0
import numpy as np
a = np.array([1,2,3,4,5])
print(a[0])

# To get elements of 3rd and 4th index,
print(a[2], a[3])

1
3 4


In [ ]:
#How to Access elements on 2nd row, 5th column in 2d Array
import numpy as np
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('5th element on 2nd row: ', a[1,4]) # [row, column] it is specifies that 1 is row'th index and 4 is column'th index.

5th element on 2nd row:  10


In [ ]:
# How to Access the third element of the second array of the first array

import numpy as np
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)
print(a[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [ ]:
# Negative Indexing
# -1 refers to the last element
import numpy as np
a = np.array([1,2,3,4,5])
print(a[-1])

5


In [ ]:
'''
Slicing in Arrays
-> It means taking elements from one given index to another given index
-> syntax: a[start : end]  or [start : end : step]
-> Start is basically considered as 0, as it is the default value.
-> End is considered as length of array
-> step is by default 1
'''

In [ ]:
#Slicing Index from 1 to 5
import numpy as np
a = np.array([1,2,3,4,5,6,7])
print(a[1:5]) # This result include the start index, but exclude the ends index
print(a[4:]) # Slicing from 4th index to end of array
print(a[:4]) # Slicing from start index to 4th index

# Negative slicing
print(a[-3:-1])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]


In [ ]:
#Step in Slicing, used to determine steps in slicing of array

#Return every other element from index 1 to index 5
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[1:5:3])

[2 5]


In [ ]:
#Return every other element from the entire array
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[::2])

[1 3 5 7 9]


In [ ]:
#From the second array, slice the element from 1 to 4
import numpy as np
a = np.array([[1,2,3,4,5], [7,8,9,0,1]])
print(a[1, 1:4])

[8 9 0]


In [ ]:
''' Data Types in Python and Numpy
-> Strings - str, for represting text data and given in form of double quotes.
-> Integers - int, for represting whole numbers
-> Floats - float, for represting decimal numbers
-> Complex - complex, for represting complex numbers
-> Booleans - bool, for represting true or false

-> i,b, u - unsigned integer, f, c- complex float, m - timedelta, O - object, S - String, U - unicode string, V - fixed chunk of memory(void) are data types in numpy.
'''

In [ ]:
#ValueError in Numpy
import numpy as np
a = np.array(['a','1','2','d'], dtype = 'i')
print(a)

# This case occurs when we try to assign integer value to the alphabet in the array

ValueError: invalid literal for int() with base 10: 'a'

In [ ]:
#Conversion of Data Type on Existing array.
# astype() function creates a copy of the array, and allows to specifiy the data type as a parameter.

import numpy as np
arr = np.array([1.12,1.32,2.56])

newarr = arr.astype('i')

print(arr)
print(newarr)
print(newarr.dtype)

[1.12 1.32 2.56]
[1 1 2]
int32


In [ ]:
'''Numpy array copy vs view
-> Both are used to view the original array.
-> The "copy" owns the data and any changes made to copy won't be affected the original array. and any changes made to original array will not affect copy.
-> It is quite opposite in the case of view as it doesn't own any data.


In [ ]:
#Copy in numpy
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42 #Doesn't affect any changes made to array

print(arr)
print(x)

y = arr.view()
arr[1] = 21 #affects the changes

print(y)
print(arr)

[42  2  3  4  5]
[1 2 3 4 5]
[42 21  3  4  5]
[42 21  3  4  5]


In [ ]:
#For checking weather array is owned or not, numpy as attribute 'base' that returns 'none' if array owns data.
import numpy as np
arr = np.array([1,2,3,4,5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)


None
[1 2 3 4 5]


In [ ]:
#Shape of an array
# It is the number of elements in each dimensions of array.
# 'shape' is an another attribute that returns tuple with each indexing numebr of corresponding elements.

#print the shape of 2D - array
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr.shape) #it gives output as 2,5 means first dim has 2 elements and second has 5

(2, 5)


In [ ]:
#Create an array with 5 dimen using ndmin using a vector with values 1,2,3,4 and verify that last dimen has value 4
import numpy as np
arr = np.array([1,2,3,4], ndmin = 5 )

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [2]:
#Re-shaping in Array - it means changing shape of array.
#The shape of array is the number of elements in each dimensions.

#Resahping 1D - 2D
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [3]:
#Reshaping 1D - 3D
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [5]:
#Unkown Dimension
#Only one dimension is allowed for unknown dimension, pass -1 into parameters, numpy will automatically determine the dimension.

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(2,3,-1)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [7]:
#Flatting of array, converting 3d array into 1d array.
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
newarr = arr.reshape(-1)
print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
#Numpy Array iterating
#Iterate means it goes to each element one by one.
# As we dealing with multi D array, we need to use for loop.
# Using 'for' loop in Numpy array.

import numpy as np
arr = np.array([1,2,3])
for x in arr:
  print(x)

1
2
3


In [17]:
 import numpy as np
 arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]
